[TS] Fix Sidebar, Stack, Tab and Tabs extended types
grommet/grommet pull request #5016
Opened 2021-02-27 19:02 UTC by miguelmarcondesf

#### What does this PR do?
Add ExtendedProps declarations for Sidebar, Stack, Tab and Tabs components, forming part of issue #4998.

#### Where should the reviewer start?
Reviewers can start from any of the files, there were independent changes only in TS declaration files

#### What testing has been done on this PR?
No additional tests were added

#### How should this be manually tested?
The import of any of the modified components in question will now have the respective _JSX.IntrinsicElements_ property 

#### Any background context you want to provide?
Discussed in the #4978

#### What are the relevant issues?
Progress track: #4998

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
Yes

2021-03-03 04:12 UTC, abnersajr approved these changes

2021-03-03 16:55 UTC, ShimiSun reviewed
Overall it looks good thanks for the contribution.

One question though, for some components, we are exporting a type `export type TabsExtendedProps` and in some other cases we are exporting an interface, e.g. `export interface StackExtendedProps`

It might be a trivial question, but wouldn't it impact the user consumption of the type differently? Should we thrive to be more consistent in the way we export?
@abnersajr

2021-03-03 17:15 UTC, miguelmarcondesf commented
Hey @ShimiSun 
I had the following problems trying to use interface on Tabs and Sidebar component, each one with a specific props conflict 
![image](https://user-images.githubusercontent.com/47646621/109843844-4bf8cf80-7c2a-11eb-9c85-96eac9d5f590.png)
![image](https://user-images.githubusercontent.com/47646621/109843880-574bfb00-7c2a-11eb-93ca-9b07b0455262.png)

2021-03-03 17:34 UTC, abnersajr commented
@ShimiSun, we need to use `export interface` always it is possible.

@miguelmarcondesf in your scenario you can do something like this:

https://github.com/grommet/grommet/pull/5021/files#diff-37524e012a5eb198c557ffc83a19486994866790935ef45e467d68096560ca90R26

Once we expect custom children, we can omit it from the `JSX.intrinsictElement` and if necessary add it to our prop.

2021-03-03 17:40 UTC, abnersajr requested changes

2021-03-03 17:40 UTC, abnersajr commented on src/js/components/Tabs/index.d.ts
> +export type TabsExtendedProps = TabsProps & JSX.IntrinsicElements['div'];
Use this as references to solve properties conflict: https://github.com/grommet/grommet/pull/5021/files#diff-37524e012a5eb198c557ffc83a19486994866790935ef45e467d68096560ca90R26

2021-03-03 17:40 UTC, abnersajr commented on src/js/components/Sidebar/index.d.ts
> +export type SidebarExtendedProps = BoxProps &
Use this as references to solve properties conflict: https://github.com/grommet/grommet/pull/5021/files#diff-37524e012a5eb198c557ffc83a19486994866790935ef45e467d68096560ca90R26

2021-03-03 20:36 UTC, miguelmarcondesf commented
Hi @ShimiSun and @abnersajr 
I followed the suggestions, now I believe everything is right.

2021-03-09 15:48 UTC, abnersajr approved these changes

2021-03-10 21:38 UTC, ShimiSun commented on src/js/components/Sidebar/index.d.ts
> +type divProps = Omit<JSX.IntrinsicElements['div'], 'onClick'>;
Which IDEA addon are you using to see this information?

2021-03-10 21:40 UTC, ShimiSun approved these changes

2021-03-10 21:52 UTC, merged